export const countries = [
    { id: 1, name: "Afghanistan", image: require('./../../img/countries/RoundedAfghanistan.png') },
    { id: 2, name: "Albania", image: require('./../../img/countries/RoundedAlbania.png') },
    { id: 3, name: "Algeria", image: require('./../../img/countries/RoundedAlgeria.png') },
    { id: 4, name: "Andorra", image: require('./../../img/countries/RoundedAndorra.png') },
    { id: 5, name: "Angola", image: require('./../../img/countries/RoundedAngola.png') },
    { id: 6, name: "Antigua and Barbuda", image: require('./../../img/countries/AntiguaAndBarbuda.png') },
    { id: 7, name: "Argentina", image: require('./../../img/countries/Argentina.png') },
    { id: 8, name: "Armenia", image: require('./../../img/countries/RoundedArmenia.png') },
    { id: 9, name: "Australia", image: require('./../../img/countries/ElementAustralia.png') },
    { id: 10, name: "Austria", image: require('./../../img/countries/RoundedAustria.png') },
    { id: 11, name: "Azerbaijan", image: require('./../../img/countries/RoundedAzerbaijan.png') },
    { id: 12, name: "Bahamas", image: require('./../../img/countries/RoundedBahamas.png') },
    { id: 13, name: "Bahrain", image: require('./../../img/countries/RoundedBahrein.png') },
    { id: 14, name: "Bangladesh", image: require('./../../img/countries/RoundedBangladesh.png') },
    { id: 15, name: "Barbados", image: require('./../../img/countries/Bahamas.png') },
    { id: 16, name: "Belarus", image: require('./../../img/countries/RoundedBelarus.png') },
    { id: 17, name: "Belgium", image: require('./../../img/countries/RoundedBelgica.png') },
    { id: 18, name: "Belize", image: require('./../../img/countries/Belize.png') },
    { id: 19, name: "Benin", image: require('./../../img/countries/ElementBenin.png') },
    { id: 20, name: "Bhutan", image: require('./../../img/countries/RoundedBhutan.png') },
    { id: 21, name: "Bolivia", image: require('./../../img/countries/Bolivia.png') },
    { id: 22, name: "Bosnia and Herzegovina", image: require('./../../img/countries/ElementBosnia.png') },
    { id: 23, name: "Botswana", image: require('./../../img/countries/RoundedBotswana.png') },
    { id: 24, name: "Brazil", image: require('./../../img/countries/RoundedBrazil.png') },
    { id: 25, name: "Brunei", image: require('./../../img/countries/RoundedBrunel.png') },
    { id: 26, name: "Bulgaria", image: require('./../../img/countries/RoundedBulgaria.png') },
    { id: 27, name: "Burkina Faso", image: require('./../../img/countries/RoundedBurkinaFaso.png') },
    { id: 28, name: "Burundi", image: require('./../../img/countries/ElementBurundi.png') },
    { id: 30, name: "Cameroon", image: require('./../../img/countries/RoundedCameroon.png') },
    { id: 31, name: "Canada", image: require('./../../img/countries/RoundedCanada.png') },
    { id: 32, name: "Cape Verde", image: require('./../../img/countries/RoundedCapeVerde.png') },
    { id: 33, name: "Central African Republic", image: require('./../../img/countries/RoundedCentralAfricanRepublic.png') },
    { id: 34, name: "Chad", image: require('./../../img/countries/RoundedChad.png') },
    { id: 35, name: "Chile", image: require('./../../img/countries/RoundedChile.png') },
    { id: 36, name: "China", image: require('./../../img/countries/RoundedChina.png') },
    { id: 37, name: "Colombia", image: require('./../../img/countries/RoundedColombia.png') },
    { id: 38, name: "Comoros", image: require('./../../img/countries/RoundedComoros.png') },
    { id: 39, name: "Congo", image: require('./../../img/countries/RoundedCongo.png') },
    { id: 40, name: "Costa Rica", image: require('./../../img/countries/RoundedCostaRica.png') },
    { id: 41, name: "Croatia", image: require('./../../img/countries/RoundedCroacia.png') },
    { id: 42, name: "Cuba", image: require('./../../img/countries/RoundedCuba.png') },
    { id: 43, name: "Cyprus", image: require('./../../img/countries/RoundedCyprus.png') },
    { id: 44, name: "Czech Republic", image: require('./../../img/countries/RoundedCzechRepublic.png') },
    { id: 45, name: "Denmark", image: require('./../../img/countries/RoundedDenmark.png') },
    { id: 46, name: "Djibouti", image: require('./../../img/countries/RoundedDjbouti.png') },
    { id: 47, name: "Dominica", image: require('./../../img/countries/RoundedDominican.png') },
    { id: 48, name: "Dominican Republic", image: require('./../../img/countries/RoundedDominicanRepublic.png') },
    { id: 49, name: "East Timor", image: require('./../../img/countries/RoundedEastTimor.png') },
    { id: 50, name: "Ecuador", image: require('./../../img/countries/RoundedEcuador.png') },
    { id: 51, name: "Egypt", image: require('./../../img/countries/RoundedEgypt.png') },
    { id: 52, name: "El Salvador", image: require('./../../img/countries/RoundedElSalvador.png') },
    { id: 53, name: "Equatorial Guinea", image: require('./../../img/countries/RoundedEquatorialGuinea.png') },
    { id: 54, name: "Eritrea", image: require('./../../img/countries/RoundedEritrea.png') },
    { id: 55, name: "Estonia", image: require('./../../img/countries/RoundedEstonia.png') },
    { id: 56, name: "Eswatini", image: require('./../../img/countries/RoundedEswatini.png') },
    { id: 57, name: "Ethiopia", image: require('./../../img/countries/ElementEthiopia.png') },
    { id: 58, name: "Fiji", image: require('./../../img/countries/RoundedFiji.png') },
    { id: 59, name: "Finland", image: require('./../../img/countries/RoundedFinland.png') },
    { id: 60, name: "France", image: require('./../../img/countries/RoundedFrance.png') },
    { id: 61, name: "Gabon", image: require('./../../img/countries/RoundedGabon.png') },
    { id: 62, name: "Gambia", image: require('./../../img/countries/RoundedGambia.png') },
    { id: 63, name: "Georgia", image: require('./../../img/countries/RoundedGeorgia.png') },
    { id: 64, name: "Germany", image: require('./../../img/countries/ElementGermany.png') },
    { id: 65, name: "Ghana", image: require('./../../img/countries/RoundedGhana.png') },
    { id: 66, name: "Greece", image: require('./../../img/countries/RoundedGreece.png') },
    { id: 67, name: "Grenada", image: require('./../../img/countries/RoundedGrenada.png') },
    { id: 68, name: "Guatemala", image: require('./../../img/countries/RoundedGuatemala.png') },
    { id: 69, name: "Guinea", image: require('./../../img/countries/RoundedGuinea.png') },
    { id: 70, name: "Guinea-Bissau", image: require('./../../img/countries/ElementGuinea-Bissau.png') },
    { id: 71, name: "Guyana", image: require('./../../img/countries/RoundedGuyana.png') },
    { id: 72, name: "Haiti", image: require('./../../img/countries/RoundedHaiti.png') },
    { id: 73, name: "Honduras", image: require('./../../img/countries/RoundedHonduras.png') },
    { id: 74, name: "Hungary", image: require('./../../img/countries/RoundedHungary.png') },
    { id: 75, name: "Iceland", image: require('./../../img/countries/ElementIceland.png') },
    { id: 76, name: "India", image: require('./../../img/countries/RoundedIndia.png') },
    { id: 77, name: "Indonesia", image: require('./../../img/countries/RoundedIndonesia.png') },
    { id: 78, name: "Iran", image: require('./../../img/countries/RoundedIran.png') },
    { id: 79, name: "Iraq", image: require('./../../img/countries/RoundedIraq.png') },
    { id: 80, name: "Ireland", image: require('./../../img/countries/RoundedIreland.png') },
    { id: 81, name: "Israel", image: require('./../../img/countries/RoundedIsrael.png') },
    { id: 82, name: "Italy", image: require('./../../img/countries/RoundedItaly.png') },
    { id: 83, name: "Jamaica", image: require('./../../img/countries/RoundedJamaica.png') },
    { id: 84, name: "Japan", image: require('./../../img/countries/RoundedJapan.png') },
    { id: 85, name: "Jordan", image: require('./../../img/countries/RoundedJordan.png') },
    { id: 86, name: "Kazakhstan", image: require('./../../img/countries/ElementKazakhstan.png') },
    { id: 87, name: "Kenya", image: require('./../../img/countries/RoundedKenya.png') },
    { id: 88, name: "Kiribati", image: require('./../../img/countries/RoundedKiribati.png') },
    { id: 89, name: "Korea, North", image: require('./../../img/countries/RoundedNorthKorea.png') },
    { id: 90, name: "Korea, South", image: require('./../../img/countries/RoundedSouthKorea.png') },
    { id: 91, name: "Kosovo", image: require('./../../img/countries/RoundedKosovo.png') },
    { id: 92, name: "Kuwait", image: require('./../../img/countries/RoundedKuwait.png') },
    { id: 93, name: "Kyrgyzstan", image: require('./../../img/countries/RoundedKyrgyzstan.png') },
    { id: 94, name: "Laos", image: require('./../../img/countries/RoundedLaos.png') },
    { id: 95, name: "Latvia", image: require('./../../img/countries/RoundedLatvia.png') },
    { id: 96, name: "Lebanon", image: require('./../../img/countries/RoundedLebanon.png') },
    { id: 97, name: "Lesotho", image: require('./../../img/countries/RoundedLesotho.png') },
    { id: 98, name: "Liberia", image: require('./../../img/countries/RoundedLiberia.png') },
    { id: 99, name: "Libya", image: require('./../../img/countries/RoundedLibya.png') },
    { id: 100, name: "Liechtenstein", image: require('./../../img/countries/RoundedLiechtenstein.png') },
    { id: 101, name: "Lithuania", image: require('./../../img/countries/ElementLithuania.png') },
    { id: 102, name: "Luxembourg", image: require('./../../img/countries/RoundedLuxemburgo.png') },
    { id: 103, name: "Madagascar", image: require('./../../img/countries/RoundedMadagascar.png') },
    { id: 104, name: "Malawi", image: require('./../../img/countries/RoundedMalawi.png') },
    { id: 105, name: "Malaysia", image: require('./../../img/countries/ElementMalaysia.png') },
    { id: 106, name: "Maldives", image: require('./../../img/countries/RoundedMaldives.png') },
    { id: 107, name: "Mali", image: require('./../../img/countries/RoundedMali.png') },
    { id: 108, name: "Malta", image: require('./../../img/countries/RoundedMalta.png') },
    { id: 109, name: "Marshall Islands", image: require('./../../img/countries/RoundedMarshallIslands.png') },
    { id: 110, name: "Mauritania", image: require('./../../img/countries/RoundedMauritania.png') },
    { id: 111, name: "Mauritius", image: require('./../../img/countries/RoundedMauritius.png') },
    { id: 112, name: "Mexico", image: require('./../../img/countries/RoundedMexico.png') },
    { id: 113, name: "Micronesia", image: require('./../../img/countries/RoundedMicronesia.png') },
    { id: 114, name: "Moldova", image: require('./../../img/countries/RoundedMoldova.png') },
    { id: 115, name: "Monaco", image: require('./../../img/countries/RoundedMonaco.png') },
    { id: 116, name: "Mongolia", image: require('./../../img/countries/RoundedMongolia.png') },
    { id: 117, name: "Montenegro", image: require('./../../img/countries/RoundedMontenegro.png') },
    { id: 118, name: "Morocco", image: require('./../../img/countries/RoundedMorroco.png') },
    { id: 119, name: "Mozambique", image: require('./../../img/countries/RoundedMozambique.png') },
    { id: 120, name: "Myanmar", image: require('./../../img/countries/RoundedMyanmar.png') },
    { id: 121, name: "Namibia", image: require('./../../img/countries/RoundedNamibia.png') },
    { id: 122, name: "Nauru", image: require('./../../img/countries/RoundedNauru.png') },
    { id: 123, name: "Nepal", image: require('./../../img/countries/RoundedNegal.png') },
    { id: 124, name: "Netherlands", image: require('./../../img/countries/RoundedNetherlands.png') },
    { id: 125, name: "New Zealand", image: require('./../../img/countries/RoundedNewZeland.png') },
    { id: 126, name: "Nicaragua", image: require('./../../img/countries/ElementNicaragua.png') },
    { id: 127, name: "Niger", image: require('./../../img/countries/RoundedNiger.png') },
    { id: 128, name: "Nigeria", image: require('./../../img/countries/RoundedNiger.png') },
    { id: 129, name: "North Macedonia", image: require('./../../img/countries/RoundedNorthMacedonia.png') },
    { id: 130, name: "Norway", image: require('./../../img/countries/RoundedNorway.png') },
    { id: 131, name: "Oman", image: require('./../../img/countries/RoundedOman.png') },
    { id: 132, name: "Pakistan", image: require('./../../img/countries/RoundedPakistan.png') },
    { id: 133, name: "Palau", image: require('./../../img/countries/RoundedPalau.png') },
    { id: 134, name: "Palestine", image: require('./../../img/countries/RoundedPalestine.png') },
    { id: 135, name: "Panama", image: require('./../../img/countries/RoundedPanama.png') },
    { id: 136, name: "Papua New Guinea", image: require('./../../img/countries/RoundedPapuaNewGuinea.png') },
    { id: 137, name: "Paraguay", image: require('./../../img/countries/RoundedParaguay.png') },
    { id: 138, name: "Peru", image: require('./../../img/countries/RoundedPeru.png') },
    { id: 139, name: "Philippines", image: require('./../../img/countries/RoundedPhilippines.png') },
    { id: 140, name: "Poland", image: require('./../../img/countries/RoundedPoland.png') },
    { id: 141, name: "Portugal", image: require('./../../img/countries/RoundedPortugal.png') },
    { id: 142, name: "Qatar", image: require('./../../img/countries/RoundedQatar.png') },
    { id: 143, name: "Romania", image: require('./../../img/countries/RoundedRomania.png') },
    { id: 144, name: "Russia", image: require('./../../img/countries/RoundedRussia.png') },
    { id: 145, name: "Rwanda", image: require('./../../img/countries/RoundedRwanda.png') },

    { id: 147, name: "Saint Lucia", image: require('./../../img/countries/RoundedSaintLucia.png') },

    { id: 149, name: "Samoa", image: require('./../../img/countries/RoundedSamoa.png') },
    { id: 150, name: "San Marino", image: require('./../../img/countries/RoundedSanMarino.png') },

    { id: 151, name: "Sao Tome and Principe", image: require('./../../img/countries/RoundedSaoTomeAndPrincipe.png') },
    { id: 152, name: "Saudi Arabia", image: require('./../../img/countries/RoundedSaudiArabia.png') },
    { id: 153, name: "Senegal", image: require('./../../img/countries/RoundedSenegal.png') },
    { id: 154, name: "Serbia", image: require('./../../img/countries/RoundedSerbia.png') },
    { id: 155, name: "Seychelles", image: require('./../../img/countries/RoundedSeychelles.png') },
    { id: 156, name: "Sierra Leone", image: require('./../../img/countries/RoundedSierraLeone.png') },
    { id: 157, name: "Singapore", image: require('./../../img/countries/RoundedSingapore.png') },
    { id: 158, name: "Slovakia", image: require('./../../img/countries/RoundedSlovakia.png') },
    { id: 159, name: "Slovenia", image: require('./../../img/countries/RoundedSlovenia.png') },
    { id: 160, name: "Solomon Islands", image: require('./../../img/countries/ElementSolomonIslands.png') },
    { id: 161, name: "Somalia", image: require('./../../img/countries/RoundedSomalia.png') },
    { id: 162, name: "South Africa", image: require('./../../img/countries/RoundedSouthAfrica.png') },
    { id: 163, name: "South Sudan", image: require('./../../img/countries/RoundedSouthSudan.png') },
    { id: 164, name: "Spain", image: require('./../../img/countries/RoundedSpanish.png') },
    { id: 165, name: "Sri Lanka", image: require('./../../img/countries/RoundedSriLanka.png') },
    { id: 166, name: "Sudan", image: require('./../../img/countries/RoundedSudan.png') },
    { id: 167, name: "Suriname", image: require('./../../img/countries/RoundedSurinamo.png') },
    { id: 168, name: "Sweden", image: require('./../../img/countries/RoundedSweden.png') },
    { id: 169, name: "Switzerland", image: require('./../../img/countries/RoundedSwitzerland.png') },
    { id: 170, name: "Syria", image: require('./../../img/countries/ElementSiria.png') },
    { id: 171, name: "Taiwan", image: require('./../../img/countries/RoundedTaiwan.png') },
    { id: 172, name: "Tajikistan", image: require('./../../img/countries/RoundedTajikistan.png') },
    { id: 174, name: "Thailand", image: require('./../../img/countries/RoundedThailand.png') },
    { id: 175, name: "Togo", image: require('./../../img/countries/RoundedTogo.png') },
    { id: 176, name: "Tonga", image: require('./../../img/countries/RoundedTonga.png') },
    { id: 177, name: "Trinidad and Tobago", image: require('./../../img/countries/RoundedTrinidadAndTobago.png') },
    { id: 178, name: "Tunisia", image: require('./../../img/countries/RoundedTunisia.png') },
    { id: 179, name: "Turkey", image: require('./../../img/countries/RoundedRepublicOfTurkiye.png') },
    { id: 180, name: "Turkmenistan", image: require('./../../img/countries/ElementTurkmenistan.png') },
    { id: 181, name: "Tuvalu", image: require('./../../img/countries/RoundedTuvalu.png') },
    { id: 182, name: "Uganda", image: require('./../../img/countries/RoundedUganda.png') },
    { id: 183, name: "Ukraine", image: require('./../../img/countries/RoundedUkraine.png') },
    { id: 184, name: "United Arab Emirates", image: require('./../../img/countries/RoundedUnitedArabEmirates.png') },
    { id: 185, name: "United Kingdom", image: require('./../../img/countries/ElementUnitedKingdom.png') },
    { id: 186, name: "United States", image: require('./../../img/countries/RoundedUnitedStates.png') },
    { id: 187, name: "Uruguay", image: require('./../../img/countries/RoundedUruguay.png') },
    { id: 188, name: "Uzbekistan", image: require('./../../img/countries/ElementUzbekistan.png') },
    { id: 189, name: "Vanuatu", image: require('./../../img/countries/RoundedVanuatu.png') },
    { id: 190, name: "Vatican City", image: require('./../../img/countries/RoundedVaticanCity.png') },
    { id: 191, name: "Venezuela", image: require('./../../img/countries/RoundedVenezuela.png') },
    { id: 192, name: "Vietnam", image: require('./../../img/countries/RoundedVietnam.png') },
    { id: 193, name: "Yemen", image: require('./../../img/countries/RoundedYemen.png') },
    { id: 194, name: "Zambia", image: require('./../../img/countries/RoundedZambia.png') },
    { id: 195, name: "Zimbabwe", image: require('./../../img/countries/RoundedZimbabwe.png') },

];
